# @package _group_
lr: 1e-4
lr_decay_step: 50

trainer:
    gpus: 1
    max_epochs: 100
    log_every_n_steps: 5
    check_val_every_n_epoch: 5
    fast_dev_run: False
    limit_train_batches: 1.0
    limit_val_batches: 1.0