# @package _group_
lr: 1e-4
lr_decay_step: 50

trainer:
    max_epochs: 75
    log_every_n_steps: 10
    check_val_every_n_epoch: 1
    fast_dev_run: False
    limit_train_batches: 0.03
    limit_val_batches: 0.1
    precision: 32